### ISSUE TITLE
Inverted stylegan

### ISSUE THREAD

**Issue by KramerKonstantin** [IIGROUP/TediGAN#10]
I trained stylegan for my data. How can I get inverted stylegan? Could you add the scripts for learning inverted stylegan to the README?

**Comment by weihaox** [comment]
Due to the scalability of our framework, there are two general ways that can be used to invert a pretrained StyleGAN. 

- Train an image encoder like in [idinvert](https://github.com/genforce/idinvert_pytorch) or other GAN inversion [methods](https://github.com/weihaox/awesome-gan-inversion) like [pSp](https://github.com/eladrich/pixel2style2pixel) or [e4e](https://github.com/omertov/encoder4editing).

- Project images to latent space directly like in [StyleGAN2Ada](https://github.com/NVlabs/stylegan2-ada#projecting-images-to-latent-space).

The above four methods are the most recommended. There are also many other gan inversion methods which you can find in our [suvery paper](https://arxiv.org/abs/2101.05278) or the [list](https://github.com/weihaox/awesome-gan-inversion). Please jump to the corresponding link to see how to invert the stylegan as needed.
