### ISSUE TITLE
LPIPS

### ISSUE THREAD

**Issue by fido20160817** [IIGROUP/TediGAN#38]
Is lower LPIPS better or higher better?
![image](https://github.com/IIGROUP/TediGAN/assets/21076140/d7728308-f469-4792-b1c6-b0e28e2f29f3)
LPIPS measures diversity, so high diversity should be good?

SDG (https://github.com/xh-liu/SDG_code) uses generated paired images to calculate LPIPS, and they note that higher LPIPS is better. 
![I2rSwFP38K](https://github.com/IIGROUP/TediGAN/assets/21076140/96e04390-f07d-4f7b-8196-4d5af614df57)

Which is correct?

**Comment by weihaox** [comment]
Thank you for your issue. I cannot recall the specific details, but it is possible that the difference is due to the way LPIPS is calculated.

One (mostly used) way to evaluate the diversity of GAN-generated images is to randomly sample two examples from the set of generated images and calculate the average LPIPS distance between them. This measures how different the two images are from each other, and a higher LPIPS score indicates greater diversity.

LPIPS score can be calculated between the generated images and the real images with the same text. This measures how close the generated images are to the real images in terms of their perceptual features, and a lower LPIPS score indicates better quality and similarity.  As I see, such calculation can (at least to some extent) reflect the diversity of the generated images because of the wide variety of real images. Additional clarification will be provided next time updating the paper. Thank you for pointing this out.

I hope this helps. Please let me know if you have any other questions.

**Comment by fido20160817** [comment]
Thanks for your reply. I can understand the two kinds of calculations in the second and third paragraphs of you reply. But I am wondering if a better similarity between the generated images and real images is expected ( for one same real image/one text, its output images should be similar to the input real image/text), which means the output images are also similar with each other, and this definitely leads to low diversity between the paired generated image from the same source input image/text. And this contradicts the description in SDG (https://github.com/xh-liu/SDG_code).

**Comment by fido20160817** [comment]
Now I recognize that the high similarity (between real images and generated images) and the high diversity (between paired generated images from the same source input image/text) are not contractionary. The two kinds of calculations of LPIPS evaluate the performance in two different views.

Thanks for your kind and timely reply!
